Repository canonical/canonicalwebteam.flask-base, pull requests merged in 2019-06, with the labels that each got.

#3 Add base template context
  CHANGELOG.md
  canonicalwebteam/flask_base/app.py
  canonicalwebteam/flask_base/context.py
  pyproject.toml
  tests/test_flask_base.py
Labels: Review: Code +1

#6 Suggested improvements
  .circleci/config.yml
  .gitignore
  README.md
  canonicalwebteam/flask_base/app.py
  canonicalwebteam/flask_base/config.py
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
  tests/test_app/deleted.yaml
  tests/test_app/humans.txt
  tests/test_app/permanent-redirects.yaml
  tests/test_app/redirects.yaml
  tests/test_app/robots.txt
  tests/test_app/templates/404.html
  tests/test_app/templates/410.html
  tests/test_app/templates/500.html
  tests/test_app/webapp/app.py
  tests/test_flask_base.py
Labels: Review: Code needed, Review: QA needed

#8 Add clear_trailing slash on before request
  canonicalwebteam/flask_base/app.py
  canonicalwebteam/flask_base/context.py
  pyproject.toml
  setup.py
  tests/test_app/webapp/app.py
  tests/test_flask_base.py
Labels: Review: Code +1, Review: QA needed
